name: AutoSort
version: '${project.version}'
main: github.curtisdh.autosort.AutoSort
api-version: 1.17 
description: A plugin which allows players to automatically sort items into appropriate chests
commands:
  reloadConfig:
    description: Reloads the config file for 'AutoSort'
    usage: /reloadConfig